/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "xfactor.h"

bool_t
xdr_Output (XDR *xdrs, Output *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->nomeGiudice, 256))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->punteggioTot))
		 return FALSE;
	return TRUE;
}
