/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FATTORE_H_RPCGEN
#define _FATTORE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct GiudicePunteggio {
	char *nomeGiudice;
	int punteggioTot;
};
typedef struct GiudicePunteggio GiudicePunteggio;

struct ClassificaGiudici {
	GiudicePunteggio currGiudice[20];
};
typedef struct ClassificaGiudici ClassificaGiudici;

struct CandOp {
	char *candidato;
	char *operazione;
};
typedef struct CandOp CandOp;

#define FATTOREX 0x20000010
#define VERSFATTOREX 1

#if defined(__STDC__) || defined(__cplusplus)
#define CLASSIFICA_GIUDICI 1
extern  ClassificaGiudici * classifica_giudici_1(void *, CLIENT *);
extern  ClassificaGiudici * classifica_giudici_1_svc(void *, struct svc_req *);
#define ESPRIMI_VOTO 2
extern  int * esprimi_voto_1(CandOp *, CLIENT *);
extern  int * esprimi_voto_1_svc(CandOp *, struct svc_req *);
extern int fattorex_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CLASSIFICA_GIUDICI 1
extern  ClassificaGiudici * classifica_giudici_1();
extern  ClassificaGiudici * classifica_giudici_1_svc();
#define ESPRIMI_VOTO 2
extern  int * esprimi_voto_1();
extern  int * esprimi_voto_1_svc();
extern int fattorex_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_GiudicePunteggio (XDR *, GiudicePunteggio*);
extern  bool_t xdr_ClassificaGiudici (XDR *, ClassificaGiudici*);
extern  bool_t xdr_CandOp (XDR *, CandOp*);

#else /* K&R C */
extern bool_t xdr_GiudicePunteggio ();
extern bool_t xdr_ClassificaGiudici ();
extern bool_t xdr_CandOp ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FATTORE_H_RPCGEN */
